[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110
lib_deps =
    espressif/esp32-camera
build_flags =
    -UARDUINO_USB_MODE
    -DARDUINO_USB_MODE=0
    -UARDUINO_USB_CDC_ON_BOOT
    -DARDUINO_USB_CDC_ON_BOOT=0
